<?php
/* SELECT id, REPLACE(LOWER(name), ' ', '-') name, chapters FROM books ORDER BY sort_order; */
$books = [
  ['id' => '1','name' => 'genesis','chapters' => '50'],
  ['id' => '2','name' => 'exodus','chapters' => '40'],
  ['id' => '4','name' => 'leviticus','chapters' => '27'],
  ['id' => '3','name' => 'numbers','chapters' => '36'],
  ['id' => '5','name' => 'deuteronomy','chapters' => '34'],
  ['id' => '10','name' => 'joshua','chapters' => '24'],
  ['id' => '6','name' => 'judges','chapters' => '21'],
  ['id' => '7','name' => 'ruth','chapters' => '4'],
  ['id' => '8','name' => '1-samuel','chapters' => '31'],
  ['id' => '9','name' => '2-samuel','chapters' => '24'],
  ['id' => '11','name' => '1-kings','chapters' => '22'],
  ['id' => '12','name' => '2-kings','chapters' => '25'],
  ['id' => '13','name' => '1-chronicles','chapters' => '29'],
  ['id' => '14','name' => '2-chronicles','chapters' => '36'],
  ['id' => '15','name' => 'ezra','chapters' => '10'],
  ['id' => '16','name' => 'nehemiah','chapters' => '13'],
  ['id' => '18','name' => 'esther','chapters' => '10'],
  ['id' => '17','name' => 'job','chapters' => '42'],
  ['id' => '19','name' => 'psalms','chapters' => '150'],
  ['id' => '20','name' => 'proverbs','chapters' => '31'],
  ['id' => '21','name' => 'ecclesiastes','chapters' => '12'],
  ['id' => '22','name' => 'song-of-songs','chapters' => '8'],
  ['id' => '23','name' => 'isaiah','chapters' => '66'],
  ['id' => '24','name' => 'jeremiah','chapters' => '52'],
  ['id' => '25','name' => 'lamentations','chapters' => '5'],
  ['id' => '26','name' => 'ezekiel','chapters' => '48'],
  ['id' => '28','name' => 'daniel','chapters' => '12'],
  ['id' => '27','name' => 'hosea','chapters' => '14'],
  ['id' => '29','name' => 'joel','chapters' => '3'],
  ['id' => '33','name' => 'amos','chapters' => '9'],
  ['id' => '30','name' => 'obadiah','chapters' => '1'],
  ['id' => '32','name' => 'jonah','chapters' => '4'],
  ['id' => '34','name' => 'micah','chapters' => '7'],
  ['id' => '37','name' => 'nahum','chapters' => '3'],
  ['id' => '35','name' => 'habakkuk','chapters' => '3'],
  ['id' => '31','name' => 'zephaniah','chapters' => '3'],
  ['id' => '36','name' => 'haggai','chapters' => '2'],
  ['id' => '38','name' => 'zechariah','chapters' => '14'],
  ['id' => '39','name' => 'malachi','chapters' => '4'],
  ['id' => '40','name' => 'matthew','chapters' => '28'],
  ['id' => '41','name' => 'mark','chapters' => '16'],
  ['id' => '42','name' => 'luke','chapters' => '24'],
  ['id' => '43','name' => 'john','chapters' => '21'],
  ['id' => '47','name' => 'acts','chapters' => '28'],
  ['id' => '46','name' => 'romans','chapters' => '16'],
  ['id' => '44','name' => '1-corinthians','chapters' => '16'],
  ['id' => '45','name' => '2-corinthians','chapters' => '13'],
  ['id' => '48','name' => 'galatians','chapters' => '6'],
  ['id' => '51','name' => 'ephesians','chapters' => '6'],
  ['id' => '52','name' => 'philippians','chapters' => '4'],
  ['id' => '49','name' => 'colossians','chapters' => '4'],
  ['id' => '50','name' => '1-thessalonians','chapters' => '5'],
  ['id' => '55','name' => '2-thessalonians','chapters' => '3'],
  ['id' => '56','name' => '1-timothy','chapters' => '6'],
  ['id' => '53','name' => '2-timothy','chapters' => '4'],
  ['id' => '58','name' => 'titus','chapters' => '3'],
  ['id' => '63','name' => 'philemon','chapters' => '1'],
  ['id' => '66','name' => 'hebrews','chapters' => '13'],
  ['id' => '54','name' => 'james','chapters' => '5'],
  ['id' => '59','name' => '1-peter','chapters' => '5'],
  ['id' => '60','name' => '2-peter','chapters' => '3'],
  ['id' => '65','name' => '1-john','chapters' => '5'],
  ['id' => '64','name' => '2-john','chapters' => '1'],
  ['id' => '57','name' => '3-john','chapters' => '1'],
  ['id' => '61','name' => 'jude','chapters' => '1'],
  ['id' => '62','name' => 'revelation','chapters' => '22']
];

/* select abbreviation, REPLACE(LOWER(name), ' ', '-') name FROM books ORDER BY sort_order */
$books_by_abbr = [
  'Gen.' => 'genesis',
  'Exo.' => 'exodus',
  'Lev.' => 'leviticus',
  'Num.' => 'numbers',
  'Deut.' => 'deuteronomy',
  'Josh.' => 'joshua',
  'Judg.' => 'judges',
  'Ruth' => 'ruth',
  '1 Sam.' => '1-samuel',
  '2 Sam.' => '2-samuel',
  '1 Kings' => '1-kings',
  '2 Kings' => '2-kings',
  '1 Chron.' => '1-chronicles',
  '2 Chron.' => '2-chronicles',
  'Ezra' => 'ezra',
  'Neh.' => 'nehemiah',
  'Esth.' => 'esther',
  'Job' => 'job',
  'Psa.' => 'psalms',
  'Prov.' => 'proverbs',
  'Eccl.' => 'ecclesiastes',
  'S.S.' => 'song-of-songs',
  'Isa.' => 'isaiah',
  'Jer.' => 'jeremiah',
  'Lam.' => 'lamentations',
  'Ezek.' => 'ezekiel',
  'Dan.' => 'daniel',
  'Hosea' => 'hosea',
  'Joel' => 'joel',
  'Amos' => 'amos',
  'Obad.' => 'obadiah',
  'Jonah' => 'jonah',
  'Micah' => 'micah',
  'Nahum' => 'nahum',
  'Hab.' => 'habakkuk',
  'Zeph.' => 'zephaniah',
  'Hag.' => 'haggai',
  'Zech.' => 'zechariah',
  'Mal.' => 'malachi',
  'Matt.' => 'matthew',
  'Mark' => 'mark',
  'Luke' => 'luke',
  'John' => 'john',
  'Acts' => 'acts',
  'Rom.' => 'romans',
  '1 Cor.' => '1-corinthians',
  '2 Cor.' => '2-corinthians',
  'Gal.' => 'galatians',
  'Eph.' => 'ephesians',
  'Phil.' => 'philippians',
  'Col.' => 'colossians',
  '1 Thes.' => '1-thessalonians',
  '2 Thes.' => '2-thessalonians',
  '1 Tim.' => '1-timothy',
  '2 Tim.' => '2-timothy',
  'Titus' => 'titus',
  'Philem.' => 'philemon',
  'Heb.' => 'hebrews',
  'James' => 'james',
  '1 Pet.' => '1-peter',
  '2 Pet.' => '2-peter',
  '1 John' => '1-john',
  '2 John' => '2-john',
  '3 John' => '3-john',
  'Jude' => 'jude',
  'Rev.' => 'revelation'
];
